name: FHiddenMine
main: FHiddenMine\Main
version: 1.0.8
api: [1.0.0]
load: POSTWORLD
author: FENGberd
commands:
 hidemine:
  description: "FHiddenMine主命令"
  usage: "/hidemine [reload|add <world>|remove <world>|list|clear]"
  permission: false
